<a href="https://colab.research.google.com/github/bhuvansun/rice-classification/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 5 Interesting Pytorch Tensor functions

A short introduction about PyTorch and about the chosen functions.

- 1. `torch.is_complex(input)`
- 2. `torch.from_numpy(ndarray)`
- 3. `torch.polar(abs, angle, *, out=None)`
- 4. `torch.eye(n, m=None, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)`
- 5. `torch.adjoint(Tensor)`

Before we begin, let's install and import PyTorch

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.is_complex()

Returns `True` if the data type of the input is a complex data type. Else, retuns `False`

In [ ]:
# Example 1 - working
x = torch.randn(2,2, dtype=torch.complex64)
x

tensor([[-0.3463-0.3036j,  1.1571-0.9975j],
        [ 0.4877+0.0192j, -0.0470+1.4872j]])

In [ ]:
torch.is_complex(x)

True

Explanation about example: \

'x' is a tensor array of size 2*2 that contains normally distributed values. Since the datatype is given as a complex datatype of 64 bits, we have complex values in the array. \

Hence, our function `torch.is_complex()` returns `True` when the tensor array 'x' is passed as the input, indicating that the tensor is of a complex datatype.


In [ ]:
# Example 2 - working
x = torch.randn(2,2, dtype=torch.float)
x

tensor([[ 0.8318, -0.6804],
        [-0.7488, -0.0688]])

In [ ]:
torch.is_complex(x)

False

Explanation about example: \

'x' is a tensor array of size 2*2 that contains normally distributed values. Since the datatype is given as a float datatype of 64 bits, we have decimal values in the array. \

Hence, our function `torch.is_complex()` returns `False` when the tensor array 'x' is passed as the input, indicating that the tensor is not of a complex datatype.

In [ ]:
# Example 3 - breaking
x = torch.ones((2, 2), dtype = torch.bool)
y = torch.ones((2, 3), dtype = torch.int)
print(x, y)

tensor([[True, True],
        [True, True]]) tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [ ]:
torch.is_complex(x, y)

TypeError: ignored

Explanation about example: \

We can only pass one parameter as input. Normally, we would expect that if multiple inputs were given, the function would return boolean values for each of the inputs respectively. But that is not the case.

Closing comments about when to use this function: \

Quickly finding out whether a given variable contains complex values or not.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - `torch.from_numpy()`

Creates a Tensor from a numpy.ndarray.

In [ ]:
import numpy as np

In [ ]:
# Example 1 - working
a = np.array([1, 2, 3])
t = torch.from_numpy(a)
t

tensor([1, 2, 3])

Explanation about example: \

'a' is a 1-dimensional numpy array containing 3 elements. \
When 'a' is passed as a parameter into the function `torch.from_numpy()`, we get the same array, but with the datatype changed to a tensor datatype.

In [ ]:
# Example 2 - working
a = np.array([[1, 2, 3], [4, 5, 6]])
t = torch.from_numpy(a)
t[0][1] = -1
t


tensor([[ 1, -1,  3],
        [ 4,  5,  6]])

Explanation about example: \

'a' is a 2-dimensional numpy array containing 2 1-dimensional arrays of 2 elements each. \

When 'a' is passed as a parameter into the function `torch.from_numpy()`, we get the same array, but with the datatype changed to a tensor datatype. \

The values can be modified in the newly created tensor array, meaning this function produces a writable tensor from a numpy array.

In [ ]:
# Example 3 - breaking
a = np.array([1, 2, 3]).setflags(write = False)
t = torch.from_numpy(a)
t

TypeError: ignored

Explanation about example: \

'a' is a 1-dimensional numpy array consisting of 3 elements. However, this time, we set the 'write' flag to `False`, meaning that we cannot modify 'a'. Hence, when we pass this as an input parameter to the function `torch.from_numpy()`, we get an error, since for the conversion to happen, we require a writable nump array.

Closing comments about when to use this function: \

Since tensor operations work only on data of tensor datatype, we can use this function to convert a numpy array to a tensor array. Incase if a datatype is not a numpy to begin with, we can convert it into a panda Dataframe using `pd.DataFrame()`, and convert it to numpy with `a.numpy()` and use the above function to get a tensor datatype.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 3 - torch.polar()

Constructs a complex tensor whose elements are Cartesian coordinates corresponding to the polar coordinates with absolute value `abs` and angle `angle`. \

out=abs⋅cos(angle)+abs⋅sin(angle)⋅j

In [ ]:
# Example 1 - working
abs = torch.tensor([1, 2], dtype=torch.float64)
angle = torch.tensor([np.pi / 2, 5 * np.pi / 4], dtype=torch.float64)
z = torch.polar(abs, angle)
z

tensor([ 6.1232e-17+1.0000j, -1.4142e+00-1.4142j], dtype=torch.complex128)

Explanation about example: \

The Cartesian coordinates (1, 2) are converted to polar coordinates in a given angle interval of π/2 to 5π/4. \

The result is a polar coordinate of absolute value and angle 6.1232e-17+1.0000j and -1.4142e+00-1.4142j, respectively.

In [ ]:
# Example 2 - working
abs = torch.tensor([2, 5], dtype=torch.float64)
angle = torch.tensor([np.pi / 3, 6 * np.pi / 5], dtype=torch.float64)
z = torch.polar(abs, angle)
z

tensor([ 1.0000+1.7321j, -4.0451-2.9389j], dtype=torch.complex128)

Explanation about example: \

The Cartesian coordinates (2, 5) are converted to polar coordinates in a given angle interval of π/3 to 6π/5.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
abs = torch.tensor([2j, 5], dtype=torch.complex64)
angle = torch.tensor([np.pi / 4, 7 * np.pi / 2], dtype=torch.float64)
z = torch.polar(abs, angle)
z

RuntimeError: ignored

Explanation about example: \

We can only enter real values in the parameter of absolute values. Complex values are not permitted.

Closing comments about when to use this function: \

Fast conversion of Cartesian coordinates into Polar coordinates.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 4 - torch.eye()

Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [ ]:
# Example 1 - working
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Explanation about example: \

For an input of 3, we get three 1D arrays, with ones aligned to form a diagonal array.

In [ ]:
# Example 2 - working
torch.eye(3, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

Explanation about example: \

Three 1D arrays with 4 elments in each, with diagonal elements having a value of one.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.eye(3, 4, 5)

TypeError: ignored

Explanation about example: \

We can only pass a 2D array parameters as input, or a single value denoting the size of the square 2D array. Diagonal arrays cannot be made for higher dimensional arrays.

Closing comments about when to use this function: \

Initialising a diagonal array without mnually entering ones at diagonal positions in a zero array.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 5 - torch.adjoint()

Returns a view of the tensor conjugated and with the last two dimensions transposed.

In [ ]:
# Example 1 - working
x = torch.arange(4, dtype=torch.float)
A = torch.complex(x, x).reshape(2, 2)
A

tensor([[0.+0.j, 1.+1.j],
        [2.+2.j, 3.+3.j]])

In [ ]:
A.adjoint()

tensor([[0.-0.j, 2.-2.j],
        [1.-1.j, 3.-3.j]])

Explanation about example: \

'x' is a torch array of elements 0, 1, 2, 3. \
'A' is a 2*2 2D array with the four integers from 0 to 3 written in complex form. \
`A.adjoint` gives the adjoint of array 'A'.

In [ ]:
# Example 2 - working
x = torch.arange(8, dtype=torch.float)
A = torch.complex(x, x).reshape(2, 2, 2)
A

tensor([[[0.+0.j, 1.+1.j],
         [2.+2.j, 3.+3.j]],

        [[4.+4.j, 5.+5.j],
         [6.+6.j, 7.+7.j]]])

In [ ]:
A.adjoint()

tensor([[[0.-0.j, 2.-2.j],
         [1.-1.j, 3.-3.j]],

        [[4.-4.j, 6.-6.j],
         [5.-5.j, 7.-7.j]]])

Explanation about example: \

Similar to the above procedure, with the only difference being that array 'A' is now a 3D array, and the addjoint is calculated accordingly.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.arange(10, dtype=torch.float)
x.adjoint()

RuntimeError: ignored

Explanation about example: \

The adjoint operation works only on 2D or higher ordered arrays, but not on 1D arrays.

Closing comments about when to use this function: \

Manually findng out the adjoint of a given matrix takes time since the formula/conversion has to be applied across all the elements. `torch.adjoint()` makes it easy to quickly find the adjoint of a matrix.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Conclusion

Not just the above 5 functions, there are many more useful functions available in the Pytorch tensor library. We only need the time to explore deeper into the unexplored part of this library.


## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html


In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
